source 'https://cdn.cocoapods.org/'

target 'macApp' do
  use_frameworks!
  platform :osx, '10.13'

  # Pods for macApp
  pod 'SDWebImage', '~> 5.20.1'
  pod 'OpenKuiklyIOSRender', :path => '../'
#  pod 'demo', :path => '../demo'

end
