source 'https://cdn.cocoapods.org/'

target 'macApp' do
  # use_frameworks!
  platform :osx, '10.13'

  # Pods for macApp
  pod 'SDWebImage', '~> 5.20.1'
  # pod 'libpag-macOS', '~> 4.5' pag-mac存在问题暂不可用
  
  pod 'OpenKuiklyIOSRender', :path => '../'
  pod 'demo', :path => '../demo'

end
